version: 0.0
os: linux
files:
  - source: /target/TestProject.war
    destination: /usr/share/tomcat/webapps
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    mode: 755
    owner: tomcat
    group: tomcat

hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root